# JATO 数据结构分析

读取 JATO-2026.1.xlsx 文件，展示 Sheet 名称、数据形状、列名和样本数据。

In [1]:
import pandas as pd
import openpyxl
from pathlib import Path

# 读取 Excel 文件
file_path = 'JATO-2026.1.xlsx'
excel_file = pd.ExcelFile(file_path)

# 所有 Sheet 名称
print('\n' + '='*60)
print('Excel Sheet 列表:')
print('='*60)
for i, sheet in enumerate(excel_file.sheet_names, 1):
    print(f'{i}. {sheet}')

============================================================
Excel Sheet 列表:
============================================================
1. 透视表
2. Data Export
3. 市场状况
4. 品牌排名
5. SUV A0
6. SUV A
7. SUV B+

In [2]:
# 为每个 Sheet 读取数据并输出结构
for sheet_name in excel_file.sheet_names:
    print(f'\n{"="*60}')
    print(f'Sheet: {sheet_name}')
    print(f'{"="*60}')
    
    df = pd.read_excel(file_path, sheet_name=sheet_name)
    print(f'\n数据度: {df.shape[0]} 行, {df.shape[1]} 列')
    print(f'\n列名 (类型):')
    for col in df.columns:
        print(f'  - {col}: {df[col].dtype}')
    
    print(f'\n第一衃数据:')
    print(df.head(3).to_string())
    
    if df.isnull().sum().sum() > 0:
        print(f'\n缺失值統計:')
        print(df.isnull().sum())

============================================================
Sheet: 透视表
============================================================

数据度: 33 行, 10 列

列名 (类型):
  - 国家: str
  - 克罗地亚: object
  - Unnamed: 2: object
  - Unnamed: 3: object
  - Unnamed: 4: object
  - Unnamed: 5: object
  - Unnamed: 6: object
  - Unnamed: 7: float64
  - Unnamed: 8: float64
  - Unnamed: 9: float64

第一衃数据:
          国家  克罗地亚 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9
0  细分市场（按车长）  (多项)        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN
1        NaN   NaN        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN
2        NaN  动总规整        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN

缺失值統計:
国家            19
克罗地亚          18
Unnamed: 2    20
Unnamed: 3    20
Unnamed: 4    20
Unnamed: 5    20
Unnamed: 6    20
Unnamed: 7    33
Unnamed: 8    33
Unnamed: 9    11
dtype: int64

============================================================
Sheet: Data Export
============================================================

数据度: 724501 行, 91 列

列名 (类型):
  - Vehicle/Volumes type: str
  - Countries: str
  - 国家: str
  - 区域划分: str
  - Registration type: str
  - JATO global segment: str
  - Make group: str
  - Make: str
  - Model group: str
  - Model: str
  - MakeModel: str
  - MakeModel%Body type%JATO global segment: str
  - 车型规整: str
  - 品牌 (英): str
  - 品牌 (中): str
  - 车型类别: str
  - 细分市场-欧: str
  - 车系: str
  - 细分市场（按车长）: str
  - Version name: object
  - Powertrain type: str
  - 动总规整: str
  - Trim level: object
  - Body type: str
  - Fuel type: str
  - 燃料规整: str
  - Transmission type: str
  - Driven wheels: str
  - CO2 level - (g/km) combined: float64
  - WLTP Emission combined: float64
  - Maximum power kW: float64
  - Battery type: str
  - Battery kwh: float64
  - 电量区间: object
  - Useable battery kilowatt hour (kWh): float64
  - Battery range: float64
  - Seating capacity: object
  - cargo volume (l): float64
  - length (mm): float64
  - width (mm): float64
  - height (mm): float64
  - wheelbase (mm): float64
  - curb weight (kg): float64
  - MSRP including delivery charge: float64
  - Base price: float64
  - Retail price: float64
  - MSRP规整: float64
  - MSRP区间: object
  - Currency: str
  - 币种换算: float64
  - 2023 Jan: int64
  - 2023 Feb: int64
  - 2023 Mar: int64
  - 2023 Apr: int64
  - 2023 May: int64
  - 2023 Jun: int64
  - 2023 Jul: int64
  - 2023 Aug: int64
  - 2023 Sep: int64
  - 2023 Oct: int64
  - 2023 Nov: int64
  - 2023 Dec: int64
  - 2024 Jan: int64
  - 2024 Feb: int64
  - 2024 Mar: int64
  - 2024 Apr: int64
  - 2024 May: int64
  - 2024 Jun: int64
  - 2024 Jul: int64
  - 2024 Aug: int64
  - 2024 Sep: int64
  - 2024 Oct: int64
  - 2024 Nov: int64
  - 2024 Dec: int64
  - 2025 Jan: int64
  - 2025 Feb: int64
  - 2025 Mar: int64
  - 2025 Apr: int64
  - 2025 May: int64
  - 2025 Jun: int64
  - 2025 Jul: int64
  - 2025 Aug: int64
  - 2025 Sep: int64
  - 2025 Oct: int64
  - 2025 Nov: int64
  - 2025 Dec: int64
  - 2026 Jan: int64
  - 2022: int64
  - 2023: int64
  - 2024: int64
  - 2025: int64

第一衃数据:
  Vehicle/Volumes type        Countries    国家 区域划分 Registration type JATO global segment Make group Make   Model group     Model    MakeModel MakeModel%Body type%JATO global segment      车型规整 品牌 (英) 品牌 (中) 车型类别 细分市场-欧  车系 细分市场（按车长）                           Version name Powertrain type  动总规整              Trim level  Body type Fuel type 燃料规整 Transmission type Driven wheels  CO2 level - (g/km) combined  WLTP Emission combined  Maximum power kW            Battery type  Battery kwh     电量区间  Useable battery kilowatt hour (kWh)  Battery range Seating capacity  cargo volume (l)  length (mm)  width (mm)  height (mm)  wheelbase (mm)  curb weight (kg)  MSRP including delivery charge  Base price  Retail price   MSRP规整  MSRP区间 Currency  币种换算  2023 Jan  2023 Feb  2023 Mar  2023 Apr  2023 May  2023 Jun  2023 Jul  2023 Aug  2023 Sep  2023 Oct  2023 Nov  2023 Dec  2024 Jan  2024 Feb  2024 Mar  2024 Apr  2024 May  2024 Jun  2024 Jul  2024 Aug  2024 Sep  2024 Oct  2024 Nov  2024 Dec  2025 Jan  2025 Feb  2025 Mar  2025 Apr  2025 May  2025 Jun  2025 Jul  2025 Aug  2025 Sep  2025 Oct  2025 Nov  2025 Dec  2026 Jan  2022  2023  2024  2025
0   Cars registrations  The Netherlands    荷兰   西欧          Business     JG Lower Medium        BMW  BMW  BMW SERIES 1  SERIES 1  BMWSERIES 1   BMWSERIES 1%hatchback%JG Lower Medium  1 Series    BMW     宝马  Car  Car C  欧系    Car A0  2.0 120DA MHEV M SPORT DESIGN EDITION            MHEV  MHEV  M SPORT DESIGN EDITION  hatchback    diesel   柴油         automatic         front                          NaN                   112.0             105.0  lithium iron phosphate         0.86  0-10kwh                                  NaN            NaN                5               NaN       4361.0      1800.0          NaN          2670.0            1470.0                         49167.0     32900.0       47917.0  47917.0  45-50k      EUR   1.0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         1         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0     0     0     1     0
1   Cars registrations          Croatia  克罗地亚   东欧          Business     JG Lower Medium        BMW  BMW  BMW SERIES 1  SERIES 1  BMWSERIES 1   BMWSERIES 1%hatchback%JG Lower Medium  1 Series    BMW     宝马  Car  Car C  欧系    Car A0                           2.0 120D DCT            MHEV  MHEV                       -  hatchback    diesel   柴油         automatic         front                          NaN                   112.0             120.0  lithium iron phosphate         0.90  0-10kwh                                  0.9            0.0                5               NaN       4361.0      1800.0       1459.0          2670.0            1570.0                         36658.0     28550.0       35688.0  35688.0  35-40k      EUR   1.0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         1         0         0         0         0         0         0         0         0         0         0         0         0         0     0     0     1     0
2   Cars registrations           Greece    希腊   南欧          Business     JG Lower Medium        BMW  BMW  BMW SERIES 1  SERIES 1  BMWSERIES 1   BMWSERIES 1%hatchback%JG Lower Medium  1 Series    BMW     宝马  Car  Car C  欧系    Car A0                     2.0 120D MHEV AUTO            MHEV  MHEV                       -  hatchback    diesel   柴油         automatic         front                          NaN                   112.0             120.0  lithium iron phosphate         0.90  0-10kwh                                  0.9            NaN                5               NaN       4361.0      1800.0       1459.0          2670.0            1570.0                         35960.0     26329.0       35960.0  35960.0  35-40k      EUR   1.0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         0         1         1         0         0         0         0         0         0         0         0         0         0         0         0         0     0     0     2     0

缺失值統計:
Vehicle/Volumes type    0
Countries               0
国家                      0
区域划分                    0
Registration type       0
                       ..
2026 Jan                0
2022                    0
2023                    0
2024                    0
2025                    0
Length: 91, dtype: int64

============================================================
Sheet: 市场状况
============================================================

数据度: 28 行, 5 列

列名 (类型):
  - Unnamed: 0: float64
  - Unnamed: 1: str
  - Unnamed: 2: float64
  - Unnamed: 3: float64
  - Unnamed: 4: float64

第一衃数据:
   Unnamed: 0 Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4
0         NaN        全车型      2024.0      2025.0      2026.0
1         NaN        Jan      4417.0      4450.0      3935.0
2         NaN        Feb      4454.0      4213.0         NaN

缺失值統計:
Unnamed: 0    28
Unnamed: 1     2
Unnamed: 2     2
Unnamed: 3     2
Unnamed: 4    24
dtype: int64

============================================================
Sheet: 品牌排名
============================================================

数据度: 32 行, 17 列

列名 (类型):
  - Unnamed: 0: float64
  - Unnamed: 1: float64
  - Unnamed: 2: object
  - Unnamed: 3: str
  - Unnamed: 4: float64
  - Unnamed: 5: float64
  - Unnamed: 6: float64
  - Unnamed: 7: float64
  - Unnamed: 8: float64
  - Unnamed: 9: float64
  - Unnamed: 10: object
  - Unnamed: 11: str
  - Unnamed: 12: float64
  - Unnamed: 13: object
  - Unnamed: 14: object
  - Unnamed: 15: float64
  - Unnamed: 16: float64

第一衃数据:
   Unnamed: 0  Unnamed: 1 Unnamed: 2 Unnamed: 3  Unnamed: 4  Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9 Unnamed: 10 Unnamed: 11  Unnamed: 12 Unnamed: 13 Unnamed: 14  Unnamed: 15  Unnamed: 16
0         NaN         NaN     年度品牌排名        NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN         NaN          NaN         NaN         NaN          NaN          NaN
1         NaN         NaN         排名         品牌      2023.0      2024.0      2025.0         NaN         NaN         NaN          排名          品牌      46023.0          环比          同比          NaN          NaN
2         NaN         NaN          1      Skoda      6536.0      8632.0      9082.0    0.052132         NaN         NaN           1          VW        514.0         593         548    -0.133221    -0.062044

缺失值統計:
Unnamed: 0     32
Unnamed: 1     32
Unnamed: 2      0
Unnamed: 3      1
Unnamed: 4      1
Unnamed: 5      1
Unnamed: 6      1
Unnamed: 7      2
Unnamed: 8     32
Unnamed: 9     32
Unnamed: 10     1
Unnamed: 11     1
Unnamed: 12     1
Unnamed: 13     1
Unnamed: 14     1
Unnamed: 15     2
Unnamed: 16     4
dtype: int64

============================================================
Sheet: SUV A0
============================================================

数据度: 63 行, 15 列

列名 (类型):
  - Unnamed: 0: float64
  - Unnamed: 1: object
  - Unnamed: 2: object
  - Unnamed: 3: object
  - Unnamed: 4: object
  - Unnamed: 5: object
  - Unnamed: 6: object
  - Unnamed: 7: object
  - Unnamed: 8: object
  - Unnamed: 9: object
  - Unnamed: 10: float64
  - Unnamed: 11: object
  - Unnamed: 12: object
  - Unnamed: 13: float64
  - Unnamed: 14: float64

第一衃数据:
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9  Unnamed: 10 Unnamed: 11 Unnamed: 12  Unnamed: 13  Unnamed: 14
0         NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN          NaN         NaN         NaN          NaN          NaN
1         NaN         排名      Model        ICE        LPG       MHEV        HEV       PHEV       REEV        BEV      46023.0          环比          同比          NaN          NaN
2         NaN          1    T-CROSS        190        NaN        NaN        NaN        NaN        NaN        NaN        190.0         247         262    -0.230769    -0.274809

缺失值統計:
Unnamed: 0     63
Unnamed: 1      8
Unnamed: 2      6
Unnamed: 3     12
Unnamed: 4     34
Unnamed: 5     16
Unnamed: 6     24
Unnamed: 7     30
Unnamed: 8     36
Unnamed: 9     30
Unnamed: 10    32
Unnamed: 11    32
Unnamed: 12    32
Unnamed: 13    33
Unnamed: 14    38
dtype: int64

============================================================
Sheet: SUV A
============================================================

数据度: 63 行, 14 列

列名 (类型):
  - Unnamed: 0: float64
  - Unnamed: 1: object
  - Unnamed: 2: object
  - Unnamed: 3: object
  - Unnamed: 4: object
  - Unnamed: 5: object
  - Unnamed: 6: object
  - Unnamed: 7: object
  - Unnamed: 8: object
  - Unnamed: 9: float64
  - Unnamed: 10: object
  - Unnamed: 11: object
  - Unnamed: 12: float64
  - Unnamed: 13: float64

第一衃数据:
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  Unnamed: 9 Unnamed: 10 Unnamed: 11  Unnamed: 12  Unnamed: 13
0         NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN         NaN         NaN         NaN          NaN          NaN
1         NaN         排名      Model        ICE       MHEV        HEV       PHEV       REEV        BEV     46023.0          环比          同比          NaN          NaN
2         NaN          1     TIGUAN         69         21        NaN          3        NaN        NaN        93.0          93          64          0.0     0.453125

缺失值統計:
Unnamed: 0     63
Unnamed: 1      6
Unnamed: 2      6
Unnamed: 3     13
Unnamed: 4     14
Unnamed: 5     27
Unnamed: 6     14
Unnamed: 7     36
Unnamed: 8     34
Unnamed: 9     32
Unnamed: 10    32
Unnamed: 11    32
Unnamed: 12    33
Unnamed: 13    35
dtype: int64

============================================================
Sheet: SUV B+
============================================================

数据度: 63 行, 13 列

列名 (类型):
  - Unnamed: 0: float64
  - Unnamed: 1: object
  - Unnamed: 2: object
  - Unnamed: 3: object
  - Unnamed: 4: object
  - Unnamed: 5: object
  - Unnamed: 6: object
  - Unnamed: 7: object
  - Unnamed: 8: float64
  - Unnamed: 9: object
  - Unnamed: 10: object
  - Unnamed: 11: float64
  - Unnamed: 12: float64

第一衃数据:
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7  Unnamed: 8 Unnamed: 9 Unnamed: 10  Unnamed: 11  Unnamed: 12
0         NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN         NaN        NaN         NaN          NaN          NaN
1         NaN         排名      Model        ICE       MHEV        HEV       PHEV        BEV     46023.0         环比          同比          NaN          NaN
2         NaN          1     KODIAQ         42         12        NaN         26        NaN        80.0         41         129      0.95122    -0.379845

缺失值統計:
Unnamed: 0     63
Unnamed: 1      6
Unnamed: 2      6
Unnamed: 3     16
Unnamed: 4     21
Unnamed: 5     34
Unnamed: 6     15
Unnamed: 7     29
Unnamed: 8     32
Unnamed: 9     32
Unnamed: 10    32
Unnamed: 11    41
Unnamed: 12    43
dtype: int64

In [3]:
# 快速汇总 - 每个 Sheet 的整体信息
print('\n' + '='*80)
print('数据结构汇总')
print('='*80)

for sheet_name in excel_file.sheet_names:
    df = pd.read_excel(file_path, sheet_name=sheet_name)
    print(f'\n[{sheet_name}]')
    print(f'  大小: {df.shape[0]:,} 行 × {df.shape[1]} 列')
    print(f'  列名: {list(df.columns)}')
    print(f'  数据类型: {dict(df.dtypes)}')
    null_count = df.isnull().sum().sum()
    if null_count > 0:
        print(f'  缺失值: {null_count} 个')

================================================================================
数据结构汇总
================================================================================

[透视表]
  大小: 33 行 × 10 列
  列名: ['国家', '克罗地亚', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']
  数据类型: {'国家': <StringDtype(storage='python', na_value=nan)>, '克罗地亚': dtype('O'), 'Unnamed: 2': dtype('O'), 'Unnamed: 3': dtype('O'), 'Unnamed: 4': dtype('O'), 'Unnamed: 5': dtype('O'), 'Unnamed: 6': dtype('O'), 'Unnamed: 7': dtype('float64'), 'Unnamed: 8': dtype('float64'), 'Unnamed: 9': dtype('float64')}
  缺失值: 214 个

[Data Export]
  大小: 724,501 行 × 91 列
  列名: ['Vehicle/Volumes type', 'Countries', '国家', '区域划分', 'Registration type', 'JATO global segment', 'Make group', 'Make', 'Model group', 'Model', 'MakeModel', 'MakeModel%Body type%JATO global segment', '车型规整', '品牌 (英)', '品牌 (中)', '车型类别', '细分市场-欧', '车系', '细分市场（按车长）', 'Version name', 'Powertrain type', '动总规整', 'Trim level', 'Body type', 'Fuel type', '燃料规整', 'Transmission type', 'Driven wheels', 'CO2 level - (g/km) combined', 'WLTP Emission combined', 'Maximum power kW', 'Battery type', 'Battery kwh', '电量区间', 'Useable battery kilowatt hour (kWh)', 'Battery range', 'Seating capacity', 'cargo volume (l)', 'length (mm)', 'width (mm)', 'height (mm)', 'wheelbase (mm)', 'curb weight (kg)', 'MSRP including delivery charge', 'Base price', 'Retail price', 'MSRP规整', 'MSRP区间', 'Currency', '币种换算', '2023 Jan', '2023 Feb', '2023 Mar', '2023 Apr', '2023 May', '2023 Jun', '2023 Jul', '2023 Aug', '2023 Sep', '2023 Oct', '2023 Nov', '2023 Dec', '2024 Jan', '2024 Feb', '2024 Mar', '2024 Apr', '2024 May', '2024 Jun', '2024 Jul', '2024 Aug', '2024 Sep', '2024 Oct', '2024 Nov', '2024 Dec', '2025 Jan', '2025 Feb', '2025 Mar', '2025 Apr', '2025 May', '2025 Jun', '2025 Jul', '2025 Aug', '2025 Sep', '2025 Oct', '2025 Nov', '2025 Dec', '2026 Jan', '2022', '2023', '2024', '2025']
  数据类型: {'Vehicle/Volumes type': <StringDtype(storage='python', na_value=nan)>, 'Countries': <StringDtype(storage='python', na_value=nan)>, '国家': <StringDtype(storage='python', na_value=nan)>, '区域划分': <StringDtype(storage='python', na_value=nan)>, 'Registration type': <StringDtype(storage='python', na_value=nan)>, 'JATO global segment': <StringDtype(storage='python', na_value=nan)>, 'Make group': <StringDtype(storage='python', na_value=nan)>, 'Make': <StringDtype(storage='python', na_value=nan)>, 'Model group': <StringDtype(storage='python', na_value=nan)>, 'Model': <StringDtype(storage='python', na_value=nan)>, 'MakeModel': <StringDtype(storage='python', na_value=nan)>, 'MakeModel%Body type%JATO global segment': <StringDtype(storage='python', na_value=nan)>, '车型规整': <StringDtype(storage='python', na_value=nan)>, '品牌 (英)': <StringDtype(storage='python', na_value=nan)>, '品牌 (中)': <StringDtype(storage='python', na_value=nan)>, '车型类别': <StringDtype(storage='python', na_value=nan)>, '细分市场-欧': <StringDtype(storage='python', na_value=nan)>, '车系': <StringDtype(storage='python', na_value=nan)>, '细分市场（按车长）': <StringDtype(storage='python', na_value=nan)>, 'Version name': dtype('O'), 'Powertrain type': <StringDtype(storage='python', na_value=nan)>, '动总规整': <StringDtype(storage='python', na_value=nan)>, 'Trim level': dtype('O'), 'Body type': <StringDtype(storage='python', na_value=nan)>, 'Fuel type': <StringDtype(storage='python', na_value=nan)>, '燃料规整': <StringDtype(storage='python', na_value=nan)>, 'Transmission type': <StringDtype(storage='python', na_value=nan)>, 'Driven wheels': <StringDtype(storage='python', na_value=nan)>, 'CO2 level - (g/km) combined': dtype('float64'), 'WLTP Emission combined': dtype('float64'), 'Maximum power kW': dtype('float64'), 'Battery type': <StringDtype(storage='python', na_value=nan)>, 'Battery kwh': dtype('float64'), '电量区间': dtype('O'), 'Useable battery kilowatt hour (kWh)': dtype('float64'), 'Battery range': dtype('float64'), 'Seating capacity': dtype('O'), 'cargo volume (l)': dtype('float64'), 'length (mm)': dtype('float64'), 'width (mm)': dtype('float64'), 'height (mm)': dtype('float64'), 'wheelbase (mm)': dtype('float64'), 'curb weight (kg)': dtype('float64'), 'MSRP including delivery charge': dtype('float64'), 'Base price': dtype('float64'), 'Retail price': dtype('float64'), 'MSRP规整': dtype('float64'), 'MSRP区间': dtype('O'), 'Currency': <StringDtype(storage='python', na_value=nan)>, '币种换算': dtype('float64'), '2023 Jan': dtype('int64'), '2023 Feb': dtype('int64'), '2023 Mar': dtype('int64'), '2023 Apr': dtype('int64'), '2023 May': dtype('int64'), '2023 Jun': dtype('int64'), '2023 Jul': dtype('int64'), '2023 Aug': dtype('int64'), '2023 Sep': dtype('int64'), '2023 Oct': dtype('int64'), '2023 Nov': dtype('int64'), '2023 Dec': dtype('int64'), '2024 Jan': dtype('int64'), '2024 Feb': dtype('int64'), '2024 Mar': dtype('int64'), '2024 Apr': dtype('int64'), '2024 May': dtype('int64'), '2024 Jun': dtype('int64'), '2024 Jul': dtype('int64'), '2024 Aug': dtype('int64'), '2024 Sep': dtype('int64'), '2024 Oct': dtype('int64'), '2024 Nov': dtype('int64'), '2024 Dec': dtype('int64'), '2025 Jan': dtype('int64'), '2025 Feb': dtype('int64'), '2025 Mar': dtype('int64'), '2025 Apr': dtype('int64'), '2025 May': dtype('int64'), '2025 Jun': dtype('int64'), '2025 Jul': dtype('int64'), '2025 Aug': dtype('int64'), '2025 Sep': dtype('int64'), '2025 Oct': dtype('int64'), '2025 Nov': dtype('int64'), '2025 Dec': dtype('int64'), '2026 Jan': dtype('int64'), '2022': dtype('int64'), '2023': dtype('int64'), '2024': dtype('int64'), '2025': dtype('int64')}
  缺失值: 3833863 个

[市场状况]
  大小: 28 行 × 5 列
  列名: ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
  数据类型: {'Unnamed: 0': dtype('float64'), 'Unnamed: 1': <StringDtype(storage='python', na_value=nan)>, 'Unnamed: 2': dtype('float64'), 'Unnamed: 3': dtype('float64'), 'Unnamed: 4': dtype('float64')}
  缺失值: 58 个

[品牌排名]
  大小: 32 行 × 17 列
  列名: ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16']
  数据类型: {'Unnamed: 0': dtype('float64'), 'Unnamed: 1': dtype('float64'), 'Unnamed: 2': dtype('O'), 'Unnamed: 3': <StringDtype(storage='python', na_value=nan)>, 'Unnamed: 4': dtype('float64'), 'Unnamed: 5': dtype('float64'), 'Unnamed: 6': dtype('float64'), 'Unnamed: 7': dtype('float64'), 'Unnamed: 8': dtype('float64'), 'Unnamed: 9': dtype('float64'), 'Unnamed: 10': dtype('O'), 'Unnamed: 11': <StringDtype(storage='python', na_value=nan)>, 'Unnamed: 12': dtype('float64'), 'Unnamed: 13': dtype('O'), 'Unnamed: 14': dtype('O'), 'Unnamed: 15': dtype('float64'), 'Unnamed: 16': dtype('float64')}
  缺失值: 145 个

[SUV A0]
  大小: 63 行 × 15 列
  列名: ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14']
  数据类型: {'Unnamed: 0': dtype('float64'), 'Unnamed: 1': dtype('O'), 'Unnamed: 2': dtype('O'), 'Unnamed: 3': dtype('O'), 'Unnamed: 4': dtype('O'), 'Unnamed: 5': dtype('O'), 'Unnamed: 6': dtype('O'), 'Unnamed: 7': dtype('O'), 'Unnamed: 8': dtype('O'), 'Unnamed: 9': dtype('O'), 'Unnamed: 10': dtype('float64'), 'Unnamed: 11': dtype('O'), 'Unnamed: 12': dtype('O'), 'Unnamed: 13': dtype('float64'), 'Unnamed: 14': dtype('float64')}
  缺失值: 426 个

[SUV A]
  大小: 63 行 × 14 列
  列名: ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']
  数据类型: {'Unnamed: 0': dtype('float64'), 'Unnamed: 1': dtype('O'), 'Unnamed: 2': dtype('O'), 'Unnamed: 3': dtype('O'), 'Unnamed: 4': dtype('O'), 'Unnamed: 5': dtype('O'), 'Unnamed: 6': dtype('O'), 'Unnamed: 7': dtype('O'), 'Unnamed: 8': dtype('O'), 'Unnamed: 9': dtype('float64'), 'Unnamed: 10': dtype('O'), 'Unnamed: 11': dtype('O'), 'Unnamed: 12': dtype('float64'), 'Unnamed: 13': dtype('float64')}
  缺失值: 377 个

[SUV B+]
  大小: 63 行 × 13 列
  列名: ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']
  数据类型: {'Unnamed: 0': dtype('float64'), 'Unnamed: 1': dtype('O'), 'Unnamed: 2': dtype('O'), 'Unnamed: 3': dtype('O'), 'Unnamed: 4': dtype('O'), 'Unnamed: 5': dtype('O'), 'Unnamed: 6': dtype('O'), 'Unnamed: 7': dtype('O'), 'Unnamed: 8': dtype('float64'), 'Unnamed: 9': dtype('O'), 'Unnamed: 10': dtype('O'), 'Unnamed: 11': dtype('float64'), 'Unnamed: 12': dtype('float64')}
  缺失值: 370 个

In [4]:
# 详细查看第一个 Sheet: 透视表
sheet1_name = '\u900f视\u8868'
df_sheet1 = pd.read_excel(file_path, sheet_name=sheet1_name)

print(f'Sheet: {sheet1_name}')
print(f'\u5f62状: {df_sheet1.shape}')
print(f'\n列名 (总计 {len(df_sheet1.columns)} 列):')
print(df_sheet1.columns.tolist())

print(f'\n前 5 行数据:')
display(df_sheet1.head())

Sheet: 透视表
形状: (33, 10)

列名 (总计 10 列):
['国家', '克罗地亚', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']

前 5 行数据:

,国家,克罗地亚,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,细分市场（按车长）,(多项),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,动总规整,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,值,ICE,MHEV,HEV,PHEV,BEV,总计,NaN,NaN,NaN
4,求和项:2025 Feb,99,94,4,33,7,237,NaN,NaN,NaN

In [5]:
# 详细查看第二个 Sheet: Data Export
sheet2_name = 'Data Export'
df_sheet2 = pd.read_excel(file_path, sheet_name=sheet2_name)

print(f'Sheet: {sheet2_name}')
print(f'\u5f62状: {df_sheet2.shape}')
print(f'\n列名 (总计 {len(df_sheet2.columns)} 列):')
print(df_sheet2.columns.tolist())

print(f'\n数据类型:')
print(df_sheet2.dtypes)

print(f'\n统计信息:')
print(df_sheet2.describe())

print(f'\n缺失值: {df_sheet2.isnull().sum().sum()}')

print(f'\n前 3 行:')
display(df_sheet2.head(3))

Sheet: Data Export
形状: (724501, 91)

列名 (总计 91 列):
['Vehicle/Volumes type', 'Countries', '国家', '区域划分', 'Registration type', 'JATO global segment', 'Make group', 'Make', 'Model group', 'Model', 'MakeModel', 'MakeModel%Body type%JATO global segment', '车型规整', '品牌 (英)', '品牌 (中)', '车型类别', '细分市场-欧', '车系', '细分市场（按车长）', 'Version name', 'Powertrain type', '动总规整', 'Trim level', 'Body type', 'Fuel type', '燃料规整', 'Transmission type', 'Driven wheels', 'CO2 level - (g/km) combined', 'WLTP Emission combined', 'Maximum power kW', 'Battery type', 'Battery kwh', '电量区间', 'Useable battery kilowatt hour (kWh)', 'Battery range', 'Seating capacity', 'cargo volume (l)', 'length (mm)', 'width (mm)', 'height (mm)', 'wheelbase (mm)', 'curb weight (kg)', 'MSRP including delivery charge', 'Base price', 'Retail price', 'MSRP规整', 'MSRP区间', 'Currency', '币种换算', '2023 Jan', '2023 Feb', '2023 Mar', '2023 Apr', '2023 May', '2023 Jun', '2023 Jul', '2023 Aug', '2023 Sep', '2023 Oct', '2023 Nov', '2023 Dec', '2024 Jan', '2024 Feb', '2024 Mar', '2024 Apr', '2024 May', '2024 Jun', '2024 Jul', '2024 Aug', '2024 Sep', '2024 Oct', '2024 Nov', '2024 Dec', '2025 Jan', '2025 Feb', '2025 Mar', '2025 Apr', '2025 May', '2025 Jun', '2025 Jul', '2025 Aug', '2025 Sep', '2025 Oct', '2025 Nov', '2025 Dec', '2026 Jan', '2022', '2023', '2024', '2025']

数据类型:
Vehicle/Volumes type      str
Countries                 str
国家                        str
区域划分                      str
Registration type         str
                        ...
2026 Jan                int64
2022                    int64
2023                    int64
2024                    int64
2025                    int64
Length: 91, dtype: object

统计信息:
       CO2 level - (g/km) combined  WLTP Emission combined  Maximum power kW  \
count                134125.000000           607807.000000     718999.000000
mean                     99.830166              115.395077        150.520880
std                      63.385059               68.051428         88.428111
min                       0.000000                0.000000          5.000000
25%                      44.000000               76.000000         96.000000
50%                     114.000000              129.000000        120.000000
75%                     134.000000              151.000000        171.000000
max                     499.000000              488.000000       1177.000000

         Battery kwh  Useable battery kilowatt hour (kWh)  Battery range  \
count  303455.000000                        105761.000000  163784.000000
mean       22.512774                            43.817794     261.949729
std        31.235520                            33.330629     217.586973
min         0.000000                             0.000000       0.000000
25%         0.500000                            14.200000      62.000000
50%         1.600000                            45.000000     190.000000
75%        35.500000                            77.000000     464.000000
max       142.870000                           142.700000     960.000000

       cargo volume (l)    length (mm)     width (mm)    height (mm)  ...  \
count        646.000000  664147.000000  649209.000000  662978.000000  ...
mean        7646.633127    4540.546021    1843.865341    1580.035701  ...
std         4078.822914     344.575136      71.336471     146.029802  ...
min            0.000000    2695.000000    1475.000000       0.000000  ...
25%         5800.000000    4341.000000    1799.000000    1465.000000  ...
50%         6000.000000    4537.000000    1841.000000    1557.000000  ...
75%         9900.000000    4758.000000    1881.000000    1658.000000  ...
max        20500.000000    7391.000000    2306.000000    3250.000000  ...

            2025 Aug       2025 Sep       2025 Oct       2025 Nov  \
count  724501.000000  724501.000000  724501.000000  724501.000000
mean        0.821242       1.093691       1.127283       1.112516
std         9.243041      14.144589      13.489971      14.458282
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         0.000000       0.000000       0.000000       0.000000
max      1585.000000    3221.000000    1898.000000    3285.000000

            2025 Dec       2026 Jan           2022           2023  \
count  724501.000000  724501.000000  724501.000000  724501.000000
mean        1.220778       0.926196      11.627966      13.124700
std        15.576215      12.669953      81.425291     114.138772
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%         0.000000       0.000000       2.000000       1.000000
max      4542.000000    3279.000000   12015.000000   15631.000000

                2024           2025
count  724501.000000  724501.000000
mean       13.102102      13.287755
std       109.696209     109.330556
min         0.000000       0.000000
25%         0.000000       0.000000
50%         0.000000       0.000000
75%         1.000000       1.000000
max     22539.000000   18909.000000

[8 rows x 58 columns]

缺失值: 3833863

前 3 行:

,Vehicle/Volumes type,Countries,国家,区域划分,Registration type,JATO global segment,Make group,Make,Model group,Model,...,2025 Aug,2025 Sep,2025 Oct,2025 Nov,2025 Dec,2026 Jan,2022,2023,2024,2025
0,Cars registrations,The Netherlands,荷兰,西欧,Business,JG Lower Medium,BMW,BMW,BMW SERIES 1,SERIES 1,...,0,0,0,0,0,0,0,0,1,0
1,Cars registrations,Croatia,克罗地亚,东欧,Business,JG Lower Medium,BMW,BMW,BMW SERIES 1,SERIES 1,...,0,0,0,0,0,0,0,0,1,0
2,Cars registrations,Greece,希腊,南欧,Business,JG Lower Medium,BMW,BMW,BMW SERIES 1,SERIES 1,...,0,0,0,0,0,0,0,0,2,0

In [6]:
# 简化汇总: 每个 Sheet 的关键信息
print('\n===== JATO Excel 数据结构简化 =====\n')

for sheet_name in excel_file.sheet_names:
    df = pd.read_excel(file_path, sheet_name=sheet_name)
    print(f'{sheet_name}')
    print(f'  算法: {df.shape[0]} 行 × {df.shape[1]} 列')
    print(f'  缺失值: {df.isnull().sum().sum()} 个')
    print(f'  数值列: {df.select_dtypes(include=["number"]).columns.tolist()}')
    print(f'  字符组列: {df.select_dtypes(include=["object"]).columns.tolist()}')
    print()

===== JATO Excel 数据结构简化 =====

透视表
  算法: 33 行 × 10 列
  缺失值: 214 个
  数值列: ['Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9']
  字符组列: ['国家', '克罗地亚', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6']

/var/folders/tv/gvfsl0090079g0tv0vqnmwy80000gn/T/ipykernel_9721/662776358.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(f'  字符组列: {df.select_dtypes(include=["object"]).columns.tolist()}')

Data Export
  算法: 724501 行 × 91 列
  缺失值: 3833863 个
  数值列: ['CO2 level - (g/km) combined', 'WLTP Emission combined', 'Maximum power kW', 'Battery kwh', 'Useable battery kilowatt hour (kWh)', 'Battery range', 'cargo volume (l)', 'length (mm)', 'width (mm)', 'height (mm)', 'wheelbase (mm)', 'curb weight (kg)', 'MSRP including delivery charge', 'Base price', 'Retail price', 'MSRP规整', '币种换算', '2023 Jan', '2023 Feb', '2023 Mar', '2023 Apr', '2023 May', '2023 Jun', '2023 Jul', '2023 Aug', '2023 Sep', '2023 Oct', '2023 Nov', '2023 Dec', '2024 Jan', '2024 Feb', '2024 Mar', '2024 Apr', '2024 May', '2024 Jun', '2024 Jul', '2024 Aug', '2024 Sep', '2024 Oct', '2024 Nov', '2024 Dec', '2025 Jan', '2025 Feb', '2025 Mar', '2025 Apr', '2025 May', '2025 Jun', '2025 Jul', '2025 Aug', '2025 Sep', '2025 Oct', '2025 Nov', '2025 Dec', '2026 Jan', '2022', '2023', '2024', '2025']
  字符组列: ['Vehicle/Volumes type', 'Countries', '国家', '区域划分', 'Registration type', 'JATO global segment', 'Make group', 'Make', 'Model group', 'Model', 'MakeModel', 'MakeModel%Body type%JATO global segment', '车型规整', '品牌 (英)', '品牌 (中)', '车型类别', '细分市场-欧', '车系', '细分市场（按车长）', 'Version name', 'Powertrain type', '动总规整', 'Trim level', 'Body type', 'Fuel type', '燃料规整', 'Transmission type', 'Driven wheels', 'Battery type', '电量区间', 'Seating capacity', 'MSRP区间', 'Currency']

/var/folders/tv/gvfsl0090079g0tv0vqnmwy80000gn/T/ipykernel_9721/662776358.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(f'  字符组列: {df.select_dtypes(include=["object"]).columns.tolist()}')

市场状况
  算法: 28 行 × 5 列
  缺失值: 58 个
  数值列: ['Unnamed: 0', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']
  字符组列: ['Unnamed: 1']

/var/folders/tv/gvfsl0090079g0tv0vqnmwy80000gn/T/ipykernel_9721/662776358.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(f'  字符组列: {df.select_dtypes(include=["object"]).columns.tolist()}')

品牌排名
  算法: 32 行 × 17 列
  缺失值: 145 个
  数值列: ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 12', 'Unnamed: 15', 'Unnamed: 16']
  字符组列: ['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 13', 'Unnamed: 14']

/var/folders/tv/gvfsl0090079g0tv0vqnmwy80000gn/T/ipykernel_9721/662776358.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(f'  字符组列: {df.select_dtypes(include=["object"]).columns.tolist()}')

SUV A0
  算法: 63 行 × 15 列
  缺失值: 426 个
  数值列: ['Unnamed: 0', 'Unnamed: 10', 'Unnamed: 13', 'Unnamed: 14']
  字符组列: ['Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 11', 'Unnamed: 12']

SUV A
  算法: 63 行 × 14 列
  缺失值: 377 个
  数值列: ['Unnamed: 0', 'Unnamed: 9', 'Unnamed: 12', 'Unnamed: 13']
  字符组列: ['Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 10', 'Unnamed: 11']

SUV B+
  算法: 63 行 × 13 列
  缺失值: 370 个
  数值列: ['Unnamed: 0', 'Unnamed: 8', 'Unnamed: 11', 'Unnamed: 12']
  字符组列: ['Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 9', 'Unnamed: 10']